
---
- hosts: localhost
  connection: local
  tasks:
    - name: Delete a resource group including resources it contains
      azure_rm_resourcegroup:
        name: ajresource
        force_delete_nonempty: yes
        state: absent
