---
# handlers file for cscfi.nis

- name: restart nis_server_daemons 
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ nis_server_daemons }}"

- name: start nis_server_daemons 
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ nis_server_daemons }}"
