---
# handlers file for cscfi.nis

- name: restart nis_client_daemons 
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ nis_client_daemons }}"

- name: start nis_client_daemons 
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ nis_client_daemons }}"
