---
- name: setup nis server 
  user: root
  hosts: nis_master
  roles:
          - nis

- name: setup nis client 
  user: root
  hosts: nis_client
  roles:
          - nisclient


- name: configuring autofs server
  hosts: autofs_server
  user: root
  roles:
          - autofs_server

- name: configuring autofs client
  hosts: autofs_client
  user: root
  roles:
          - autofs_client

