---
# tasks file for docker
- name: Check if old versions are deleted
  package:
    name:
       - docker
       - docker-common
       - docker-engine
    state: absent

- name: Add Docker gpg
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add docker repo
  get_url:
    url: "{{ docker_repo_url }}"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Check if docker is started and enabled
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: To get current userid to add in docker group
  set_fact:
    username: "{{ lookup('env','USER') }}"

- name: Add current user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
